export default [
  {
    name: 'Aluguel',
    expectation: '500,00',
    reality: '650,20',
    category: 'Estrutural',
    color: 'Blue',
  },
  {
    name: 'Condominio',
    expectation: '300,00',
    reality: '302,20',
    category: 'Estrutural',
    color: '#181818',
  },
  {
    name: 'Luz',
    expectation: '500,00',
    reality: '650,20',
    category: 'Estrutural',
    color: 'Blue',
  },
  {
    name: 'Gás',
    expectation: '500,00',
    reality: '650,20',
    category: 'Estrutural',
    color: 'Blue',
  },
  {
    name: 'Warren',
    expectation: '500,00',
    reality: '650,20',
    category: 'Investimento',
    color: 'Yellow',
  },
  {
    name: 'Praia',
    expectation: '500,00',
    reality: '650,20',
    category: 'Viagens',
    color: 'Red',
  },
  {
    name: 'Sitio',
    expectation: '500,00',
    reality: '650,20',
    category: 'Viagens',
    color: 'Red',
  },
];
